# Kubernetes Deployment for AI Agent
# Apply: kubectl apply -f infra/k8s.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: starter-agent
  labels:
    app: starter-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: starter-agent
  template:
    metadata:
      labels:
        app: starter-agent
    spec:
      containers:
        - name: agent
          image: your-registry/starter-agent:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: agent-secrets
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: starter-agent-svc
spec:
  selector:
    app: starter-agent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: starter-agent-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: starter-agent
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
